### ISSUE TITLE
Build Failure on Linux due to Capitalization

### ISSUE THREAD

**Issue by hi117** [ThibaultReuille/raindance#1]
Here is a patch to fix the issue.
diff --git a/Core/GUI/WindowManager.hh b/Core/GUI/WindowManager.hh
index 2c5e685..47bf0f5 100644
--- a/Core/GUI/WindowManager.hh
+++ b/Core/GUI/WindowManager.hh
@@ -1,7 +1,7 @@
 #pragma once

 #include <raindance/Core/Manager.hh>
-#include <raindance/Core/Gui/Window.hh>
+#include <raindance/Core/GUI/Window.hh>

 class WindowManager : public Manager<Window>
 {

**Comment by light44** [comment]
This still causes a build failure when following the build instructions from http://www.opengraphiti.com/
